/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'CreateOrder': ApiRouteHandler<{ id: string; number: string; meals: Array<'a-vontade' | 'rodizio' | 'por-quilo'>; beveareges: Array<'refrigerante' | 'suco-natural' | 'agua' | 'suco'>; deserts: Array<'pudim' | 'mousse' | 'sorvete'> }, unknown, never>
    'GetOrder': ApiRouteHandler<{ string: string }, unknown, never>
  }
}