/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'CreateProduct': ApiRouteHandler<{ type: 'sobremesa' | 'bebida-nao-alcolicas' | 'bebidas-alcolicas'; name: string; price: string }, unknown, never>
    'GetOrder': ApiRouteHandler<{ string: string }, unknown, never>
    'GetAllProducts': ApiRouteHandler<Array<{ id?: string; type: 'sobremesa' | 'bebida-nao-alcolicas' | 'bebidas-alcolicas'; name: string; price: string }>, unknown, never>
    'CreateMeal': ApiRouteHandler<{ name: string; price: string; weekendPrice?: string }, unknown, never>
    'GetMeals': ApiRouteHandler<Array<{ id?: string; name: string; price: string; weekendPrice?: string }>, unknown, never>
    'CreateOrder': ApiRouteHandler<{ number: string; meals: Array<{ id?: string; name: string; price: string; weekendPrice?: string }>; otherItems?: Array<{ id?: string; type: 'sobremesa' | 'bebida-nao-alcolicas' | 'bebidas-alcolicas'; name: string; price: string }> }, unknown, never>
  }
}